{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cloudformation-operator-manager-rolebinding
  labels:
  {{- include "cloudformation-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cloudformation-operator-manager-role
subjects:
- kind: ServiceAccount
  name: {{ include "cloudformation-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cloudformation-operator-proxy-rolebinding
  labels:
  {{- include "cloudformation-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cloudformation-operator-proxy-role
subjects:
- kind: ServiceAccount
  name: {{ include "cloudformation-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}