{{- if .Values.rbac.create }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cloudformation-operator-leader-election-rolebinding
  labels:
  {{- include "cloudformation-operator.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "cloudformation-operator.serviceAccountName" . }}
roleRef:
  kind: Role
  name: cloudformation-operator-leader-election-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}