{{- if .Values.rbac.create }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "cloudformation-operator.name" . }}
  labels:
{{ include "cloudformation-operator.helmStandardLabels" . | indent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ template "cloudformation-operator.name" . }}
roleRef:
  kind: Role
  name: {{ template "cloudformation-operator.name" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}