{{- if .Values.rbac.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
{{ include "cloudformation-operator.helmStandardLabels" . | indent 4 }}
  name: {{ template "cloudformation-operator.name" . }}
{{- end -}}