dist: trusty

os:
- linux

language: go

go:
- "1.13"
- tip

env:
- GO111MODULE=on

install:
- go get github.com/mattn/goveralls
- go get github.com/golang/dep/cmd/dep

script:
- roveralls
- goveralls -coverprofile=roveralls.coverprofile -service=travis-ci
