[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "~v1.13.48"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "~1.0.5"

[[constraint]]
  name = "github.com/alecthomas/kingpin"
  version = "~2.2.6"

[[constraint]]
  branch = "release-1.10"
  name = "k8s.io/apimachinery"

[[constraint]]
  branch = "master"
  name = "github.com/operator-framework/operator-sdk"

[prune]
  go-tests = true
  non-go = true
  unused-packages = true
