apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: stacks.cloudformation.linki.space
spec:
  group: cloudformation.linki.space
  version: v1alpha1
  scope: Namespaced
  names:
    plural: stacks
    singular: stack
    kind: Stack
    shortNames:
    - cfs
