---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cloudformation-admin
  namespace: default
rules:
- apiGroups: ["cloudformation.linki.space"]
  resources: ["stacks"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cloudformation-operator-rbac
  namespace: default
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
roleRef:
  kind: ClusterRole
  name: cloudformation-admin
  apiGroup: rbac.authorization.k8s.io
